"""
Cross-language Yjs compatibility smoke test.
Run: uv run python scripts/yjs-cross-lang-smoke.py
Reads the binary update generated by the JS smoke test and verifies y-py can decode it.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))

import y_py as Y  # noqa: E402


def main():
    bin_path = ROOT / "frontend" / "scripts" / "yjs_smoke_update.bin"
    if not bin_path.exists():
        print(f"ERROR: Binary file not found at {bin_path}")
        print("Run the JS smoke test first: node frontend/scripts/yquill-smoke.mjs")
        sys.exit(1)

    state = bin_path.read_bytes()
    print(f"Loaded {len(state)} bytes from JS smoke test.")

    doc = Y.YDoc()
    try:
        Y.apply_update(doc, state)
    except Exception as e:
        print(f"ERROR: y-py failed to decode JS-encoded update: {e}")
        sys.exit(1)

    ytext = doc.get_text("quill")
    text = str(ytext)
    print(f"Decoded text: '{text}'")
    assert text == "hello beautiful world", f"Expected 'hello beautiful world', got '{text}'"
    print("PASSED: Cross-language Yjs roundtrip verified.")
    sys.exit(0)


if __name__ == "__main__":
    main()
